# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.
# See also https://symfony.com/doc/current/service_container/import.html

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
# config/services.yaml (ou un fichier custom/relationships.yaml)
parameters:
    app.relationship_codes:
        GRAND_PARENT_PETIT_ENFANT: 'R_GPPE'
        PARENT_ENFANT: 'R_PE'
        FRERE_SOEUR: 'R_FS'
        ONCLE_NEVEU: 'R_ON'
        TIERS: 'R_T'

    app.fiscal_abatement_amounts_in_cents:
        parent_enfant: 10000000
        grand_parent_petit_enfant: 3186500
        epoux: 8072400
        don_sarkozy_cumulable: 3186500

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\Service\GenealogyService:
        arguments:
            $relationshipCodes: '%app.relationship_codes%' # <-- INJECTION ICI
    
    App\DataFixtures\AppFixtures:
        arguments:
            # Injection des paramètres hérités par AppFixtures
            $hasher: '@Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface'
            $parameterBag: '@parameter_bag'
            # Injection des variables d'environnement
            $adminEmail: '%env(ADMIN_EMAIL)%'
            $adminPassword: '%env(ADMIN_PASSWORD)%'

    App\Service\SimulationPlanningService:
            arguments:
                $abatementAmountsInCents: '%app.fiscal_abatement_amounts_in_cents%'
            # La ligne ci-dessous est souvent nécessaire si vous utilisez un custom service
            # mais l'autowiring devrait suffire si les arguments sont typés.
            # autowire: true