# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.
# See also https://symfony.com/doc/current/service_container/import.html

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    # nombre de personnes minimun dans l'affichage d'un arbre généalogique
    app.tree.min_people_count: 4

    app.relationship_codes:
        GRAND_PARENT_PETIT_ENFANT: 'R_GPPE'
        PARENT_ENFANT: 'R_PE'
        FRERE_SOEUR: 'R_FS'
        ONCLE_NEVEU: 'R_ON'
        TIERS: 'R_T'
        
    # Paramètres d'environnement nécessaires pour les commandes/fixtures
    app.admin_email: '%env(ADMIN_EMAIL)%'
    app.admin_password: '%env(ADMIN_PASSWORD)%'
    # Le paramètre app.fiscal_abatement_amounts_in_cents a été supprimé.

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    # -------------------------------------------------------------------------
    # Configurations Spécifiques
    # -------------------------------------------------------------------------

    # Configuration du service pour l'injection des codes relationnels
    App\Service\GenealogyService:
        arguments:
            $relationshipCodes: '%app.relationship_codes%' 

    # Configuration de la classe Fixtures (si vous continuez à l'utiliser)
    App\DataFixtures\AppFixtures:
        arguments:
            $adminEmail: '%app.admin_email%'
            $adminPassword: '%app.admin_password%'

    # Configuration de la COMMANDE d'initialisation pour l'injection des variables d'environnement
    App\Command\InitAppCommand:
        arguments:
            # Nommer explicitement les arguments pour les paramètres d'environnement
            $adminEmailParam: '%app.admin_email%'
            $adminPasswordParam: '%app.admin_password%'

    App\EventListener\UserExpirationCheckListener:
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onSecurityInteractiveLogin }

    App\Service\CityImportService:
        arguments:
            # Assigner explicitement le paramètre système %kernel.project_dir% 
            # à l'argument $kernelProjectDir de la méthode __construct
            $kernelProjectDir: '%kernel.project_dir%'